all:
	poetry run python naver.py
	poetry run python kakao.py
	poetry run python line.py
	poetry run python coupang.py
	poetry run python baemin.py
	poetry run python daangn.py
	poetry run python hpcnt.py
	poetry run python devsisters.py
	poetry run python flipster.py
	poetry run python tagger.py
